Repository KU-Taverse/user-server-BE-, pull requests merged in 2024-09, with the labels that each got.

#22 [Test] circuitbreaker test
  src/main/java/ku/user/user/service/TestService.java
  src/main/resources/application.yml
  src/test/java/ku/user/client/GameServiceClientTest.java
Labels: test

#23 [Feat] Spring Security 로그인 변경
  src/main/java/ku/user/response/ApiResponse.java
  src/main/java/ku/user/response/ErrorResponse.java
  src/main/java/ku/user/security/AuthenticationFilter.java
  src/main/java/ku/user/security/CustomLoginFailureHandler.java
  src/main/java/ku/user/security/WebSecurity.java
  src/main/java/ku/user/user/controller/UserController.java
  src/main/java/ku/user/user/domain/CreateUser.java
  src/main/java/ku/user/user/domain/RequestLogin.java
  src/main/java/ku/user/user/domain/UserDto.java
  src/main/java/ku/user/user/infrastructure/entity/UserEntity.java
  src/main/java/ku/user/user/service/UserService.java
  src/main/java/ku/user/user/service/UserServiceImpl.java
Labels: 리팩토링, 기능구현

#26 Refactor/package
  src/main/java/ku/user/domain/character/controller/CharacterController.java
  src/main/java/ku/user/domain/character/dao/CharacterRepository.java
  src/main/java/ku/user/domain/character/domain/Character.java
  src/main/java/ku/user/domain/character/domain/CharacterType.java
  src/main/java/ku/user/domain/character/dto/request/PutCharacterRequest.java
  src/main/java/ku/user/domain/character/dto/request/SaveCharacterRequest.java
  src/main/java/ku/user/domain/character/dto/response/CheckCharacterExistResponse.java
  src/main/java/ku/user/domain/character/dto/response/DeleteCharacterResponse.java
  src/main/java/ku/user/domain/character/dto/response/FindCharacterByEmailResponse.java
  src/main/java/ku/user/domain/character/dto/response/PutCharacterResponse.java
  src/main/java/ku/user/domain/character/dto/response/SaveCharacterResponse.java
  src/main/java/ku/user/domain/character/service/CharacterService.java
Labels: 기능구현

#27 [Feat] sologame 기록 저장
  build.gradle
  src/main/java/ku/user/domain/Ranking/controller/RhythmScoreController.java
  src/main/java/ku/user/domain/Ranking/controller/SteppingStonesScoreController.java
  src/main/java/ku/user/domain/Ranking/domain/RhythmScore.java
  src/main/java/ku/user/domain/Ranking/domain/Status.java
  src/main/java/ku/user/domain/Ranking/domain/SteppingStonesScore.java
  src/main/java/ku/user/domain/Ranking/dto/request/SaveRhythmRequest.java
  src/main/java/ku/user/domain/Ranking/dto/request/SaveSteppingRequest.java
  src/main/java/ku/user/domain/Ranking/dto/response/SaveRhythmResponse.java
  src/main/java/ku/user/domain/Ranking/dto/response/SaveSteppingResponse.java
  src/main/java/ku/user/domain/Ranking/infrastructure/RhythmScoreRepository.java
  src/main/java/ku/user/domain/Ranking/infrastructure/SteppingScoreRepository.java
  src/main/java/ku/user/domain/Ranking/service/RhythmScoreService.java
  src/main/java/ku/user/domain/Ranking/service/RhythmScoreServiceImpl.java
  src/main/java/ku/user/domain/Ranking/service/SteppingStonesScoreService.java
  src/main/java/ku/user/domain/Ranking/service/SteppingStonesScoreServiceImpl.java
Labels: 기능구현

#32 [Feat] ranking기능 개발
  build.gradle
  src/main/java/ku/user/domain/ranking/controller/RhythmScoreController.java
  src/main/java/ku/user/domain/ranking/controller/SteppingStonesScoreController.java
  src/main/java/ku/user/domain/ranking/domain/RhythmRanking.java
  src/main/java/ku/user/domain/ranking/domain/RhythmScore.java
  src/main/java/ku/user/domain/ranking/domain/Status.java
  src/main/java/ku/user/domain/ranking/domain/SteppingStonesRanking.java
  src/main/java/ku/user/domain/ranking/domain/SteppingStonesScore.java
  src/main/java/ku/user/domain/ranking/dto/request/SaveRhythmRequest.java
  src/main/java/ku/user/domain/ranking/dto/request/SaveSteppingRequest.java
  src/main/java/ku/user/domain/ranking/dto/response/GetRankingResponse.java
  src/main/java/ku/user/domain/ranking/dto/response/SaveRhythmResponse.java
  src/main/java/ku/user/domain/ranking/dto/response/SaveSteppingResponse.java
  src/main/java/ku/user/domain/ranking/infrastructure/RhythmScoreRepository.java
  src/main/java/ku/user/domain/ranking/infrastructure/SteppingScoreRepository.java
  src/main/java/ku/user/domain/ranking/service/RankingService.java
  src/main/java/ku/user/domain/ranking/service/RankingServiceImpl.java
  src/main/java/ku/user/domain/ranking/service/RhythmScoreService.java
  src/main/java/ku/user/domain/ranking/service/RhythmScoreServiceImpl.java
  src/main/java/ku/user/domain/ranking/service/SteppingStonesScoreService.java
  src/main/java/ku/user/domain/ranking/service/SteppingStonesScoreServiceImpl.java
  src/main/java/ku/user/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/ku/user/user/infrastructure/UserRepositoryImplTest.java
  src/test/resources/application.yml
Labels: 기능구현
